samples: "samples.tsv"
units: "units.tsv"

reference:
    assembly: hg38
    genome: "/vol/tiny/MaMel-Neoantigens/Neoantigen_Prediction/ref/hg38/genome.fa"
    call_regions: "ref/call_regions.bed.gz"
    hla_data: "ref/HLA_Data/hla_reference_dna.fasta"

params:
    bwa:
        "-M"
    strelka:
        "--exome"
    razers3:
        "-i 95 -m 1 -dr 0"
    netMHCpan:
        "-BA -l 9 -s -xls"
    netMHCIIpan:
        "-length 15 -s -xls"
    optitype:
        "ref/optitype.config.ini"
    microphaser:
        windowlen: 60

