samples: "samples.tsv"
units: "units.tsv"

# boolean if read trimming should be skipped
trimming:
  skip: true

calling:
  delly:
    activate: true
  freebayes:
    activate: true
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: scenario.yaml
  # See http://snpeff.sourceforge.net/SnpSift.html#filter
  filter: ANN[*].IMPACT has MODERATE
  fdr-control:
    threshold: 0.05
    events: 
      complete:
        varlociraptor: 
          - "somatic"
          - "germline"

reference:
  assembly: hg38
  genome: genome.fa
  call_regions: "ref/call_regions.bed.gz"
  hla_data: "ref/HLA_Data/hla_reference_dna.fasta"
  transcriptome: "path/to/transcript_reference"
  gtfs: /vol/tiny/christoph-MPM/NeoPred/gtfs
  n_chromosomes: 25
  snpeff: GRCh38.86

params:
  bwa:
    "-M"
  strelka:
    "--exome"
  razers3:
    "-i 95 -m 1 -dr 0"
  microphaser:
    window_len:
        60
  netMHCpan:
    "-BA -l 9 -s -xls"
  netMHCIIpan:
    "-s -xls"
  optitype:
    "ref/optitype.config.ini"
  kallisto:
    "-b 100"
