samples: "samples.tsv"
units: "units.tsv"

# boolean if read trimming should be skipped
trimming:
  skip: true

reference:
    assembly: hg38
    genome: "path/to/genome"
    call_regions: "ref/call_regions.bed.gz"
    hla_data: "ref/HLA_Data/hla_reference_dna.fasta"
    transcriptome: "path/to/transcript_reference"
    gtfs: /vol/tiny/christoph-MPM/NeoPred/gtfs

params:
    bwa:
        "-M"
    strelka:
        "--exome"
    razers3:
        "-i 95 -m 1 -dr 0"
    microphaser:
        window_len:
            60
    netMHCpan:
        "-BA -l 9 -s -xls"
    netMHCIIpan:
        "-s -xls"
    optitype:
        "ref/optitype.config.ini"
    kallisto:
        "-b 100"
