samples: "samples.tsv"
units: "units.tsv"

reference:
    assembly: hg38
    genome: "path/to/genome"
    call_regions: "ref/call_regions.bed.gz"
    hla_data: "ref/HLA_Data/hla_reference_dna.fasta"

params:
    bwa:
        "-M"
    strelka:
        "--exome"
    razers3:
        "-i 95 -m 1 -dr 0"
    netMHCpan:
        "-BA -l 9 -s -xls"
    optitype:
        "ref/optitype.config.ini"

