samples: "config/samples.tsv"
units: "config/units.tsv"


neoantigen_prediction:
  activate: true


ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38


params:
  microphaser:
    # window_len should be at least 3 times the longest peptide_len specified below
    variant_sets:
      normal: "normal_only"
      tumor: "tumor_only"
  netMHCpan:
    activate: true
    peptide_len: 9
    params: "-BA -s"
    # Please download netMHCpan manually from:
    # https://services.healthtech.dtu.dk/service.php?NetMHCpan-4.1
    # To make the `netMHCpan` script work, you need to fix its first line in
    # in addition to the other edits described for a complete install. To use
    # the conda-provided tcsh installation, it needs to read (without quotes):
    # "#!/usr/bin/env tcsh"
    location: "../netMHCpan-4.1"
  netMHCIIpan:
    activate: false
    peptide_len: 15
    params: "-BA -s"
    # Please download netMHCIIpan manually from:
    # https://services.healthtech.dtu.dk/service.php?NetMHCIIpan-4.1
    # To make the `netMHCIIpan` script work, you need to fix its first line in
    # in addition to the other edits described for a complete install. To use
    # the conda-provided tcsh installation, it needs to read (without quotes):
    # "#!/usr/bin/env tcsh"
    location: "../netMHCIIpan-4.1"

