samples: "config/samples.tsv"
units: "config/units.tsv"

# boolean if read trimming should be skipped
trimming:
  skip: true

calling:
  delly:
    activate: true
  freebayes:
    activate: true
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: config/scenario.yaml
  # See http://snpeff.sourceforge.net/SnpSift.html#filter
  filter: ANN[*].IMPACT has MODERATE
  fdr-control:
    threshold: 0.05
    events: 
      complete:
        varlociraptor: 
          - "somatic"
          - "germline"
      somatic:
        varlociraptor:
          - "somatic"
      germline:
        varlociraptor:
          - "germline"

fusion:
  arriba:
    blacklist:
     "arriba_blacklist"

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 98
  # Ensembl release to use for SnpEff annotation (sometimes, the latest Ensembl release is not available in SnpEff)
  snpeff_release: 86
  # Genome build
  build: GRCh38

reference:
  assembly: hg38
  genome: test/genome.fa
  call_regions: "config/call_regions.bed.gz"
  hla_data: "config/HLA_Data/hla_reference_dna.fasta"
  transcriptome: "path/to/transcript_reference"
  gtfs: path/to/gtfs
  annotation: complete.gtf
  n_chromosomes: 25
  snpeff: GRCh38.86

params:
  bwa:
    "-M"
  strelka:
    "--exome"
  razers3:
    "-i 95 -m 1 -dr 0"
  microphaser:
    window_len:
        60
  netMHCpan:
    "-BA -l 9 -s -xls"
  netMHCIIpan:
    "-length 15 -s -xls"
  optitype:
    "ref/optitype.config.ini"
  kallisto:
    "-b 100"
  star:
    "--outSAMmapqUnique 60"
