samples:
  tumor:
    resolution: 100
    universe: "[0.0,1.0]"
    contamination:
      by: normal
      fraction: {{ 1.0 - samples[samples["type"] == "tumor"]["purity"][0] }}
  normal:
    resolution: 5
    universe: "0.0 | 0.5 | 1.0 | ]0.0,0.5["

events:
  germline: "normal:1.0 | normal:]0.0,0.5]"
  somatic: "tumor:]0.0,1.0] & normal:0.0"
