samples: "config/samples.tsv"
units: "config/units.tsv"


tmb:
  activate: true
  coding_genome_size: 3e7
  # Name of the tumor sample in the scenario.yaml.
  tumor_sample: tumor
  somatic_events:
    - somatic


epitope_prediction:
  activate: true


affinity:
  netMHCpan:
    activate: true
    params: "-BA -l 9 -s -xls"
    location: "../netMHCpan-4.0"
  netMHCIIpan:
    activate: false
    params: "-length 15 -s -xls"
    location: "../netMHCIIpan-4.0"


ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38


annotations:
  vep:
    params: "--everything"
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool

params:
  microphaser:
    window_len:
        33
    peptide_len:
      netMHCpan:
          9
      netMHCIIpan:
          15
    events:
      tumor: "tumor_only"
      normal: "normal_only"
