samples: "config/samples.tsv"
units: "config/units.tsv"


epitope_prediction:
  activate: true


affinity:
  netMHCpan:
    activate: true
    params: "-BA -l 9 -s -xls"
    # Please download netMHCpan manually from:
    # https://services.healthtech.dtu.dk/service.php?NetMHCpan-4.1
    # To make the `netMHCpan` script work, you need to fix its first line in
    # in addition to the other edits described for a complete install. To use
    # the conda-provided tcsh installation, it needs to read (without quotes):
    # "#!/usr/bin/env tcsh"
    location: "../netMHCpan-4.1"
  netMHCIIpan:
    activate: false
    params: "-length 15 -s -xls"
    # Please download netMHCIIpan manually from:
    # https://services.healthtech.dtu.dk/service.php?NetMHCIIpan-4.1
    # To make the `netMHCIIpan` script work, you need to fix its first line in
    # in addition to the other edits described for a complete install. To use
    # the conda-provided tcsh installation, it needs to read (without quotes):
    # "#!/usr/bin/env tcsh"
    location: "../netMHCIIpan-4.1"


ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38


annotations:
  vep:
    params: "--everything"
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool

params:
  microphaser:
    window_len:
        33
    peptide_len:
      netMHCpan:
          9
      netMHCIIpan:
          15
    events:
      tumor: "tumor_only"
      normal: "normal_only"
