samples: "config/samples.tsv"
units: "config/units.tsv"

# boolean if read trimming should be skipped
trimming:
  activate: false

remove_duplicates:
  activate: false

calling:
  freebayes:
    activate: false
  # See https://varlociraptor.github.io/docs/calling/#generic-variant-calling
  scenario: config/scenario.yaml
  filter:
    # Filter candidate variants (this filter helps to keep the number of evaluated candidates small).
    # It should ideally generate a superset of all other filters defined below.
    # Annotation of candidate variants tries to be as fast as possible, only using VEP
    # default parameters.
    candidates: ""
    # Add any number of named filters here. They will be applied independenty,
    # and can be referred in FDR control below to generate calls for different events.
    # In particular, you can also filter by ID or dbsnp annotations here.
    # See http://snpeff.sourceforge.net/SnpSift.html#filter
    filtername: "ANN['IMPACT'] != 'MODIFIER'"
  fdr-control:
    threshold: 0.05
    events: 
      complete:
        varlociraptor: 
          - "somatic"
          - "germline"
      somatic:
        varlociraptor:
          - "somatic"
      germline:
        varlociraptor:
          - "germline"

fusion:
  arriba:
    activate: true
    blacklist:
     "arriba_blacklist"
    params:
      "-T -P"

tmb:
  activate: true
  coding_genome_size: 3e7
  # Name of the tumor sample in the scenario.yaml.
  tumor_sample: tumor
  somatic_events:
    - somatic


epitope_prediction:
  activate: true


affinity:
  netMHCpan:
    activate: true
    params: "-BA -l 9 -s -xls"
    location: "../netMHCpan-4.0"
  netMHCIIpan:
    activate: false
    params: "-length 15 -s -xls"
    location: "../netMHCIIpan-4.0"


HLAtyping:
  # activate to use razers3 to pre-filter reads before using optitype
  optitype_prefiltering:
    activate: true
  optitype_data: "config/HLA_Data/hla_reference_dna.fasta"
  # activate to predict MHC-I and MHC-II alleles with HLA-LA
  HLA_LA:
    activate: false


ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38


annotations:
  vep:
    params: "--everything"
    plugins:
      # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
      # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool

params:
  cutadapt: ""
  bwa:
    "-M"
  picard:
    MarkDuplicates:
      "VALIDATION_STRINGENCY=LENIENT"
  gatk:
    BaseRecalibrator: "--tmp-dir tmp"
    applyBQSR: ""
  strelka:
    config:
      "--exome"
    run:
      "--mode local"
  razers3:
    "-i 95 -m 1 -dr 0"
  optitype:
    ""
  microphaser:
    window_len:
        33
    peptide_len:
      netMHCpan:
          9
      netMHCIIpan:
          15
  kallisto:
    "-b 100"
  star: >-
    --outSAMmapqUnique 60 --outSAMtype BAM Unsorted --chimSegmentMin 10 --chimOutType WithinBAM SoftClip
    --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0
    --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3
