$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

definitions:
  filterentry:
    type: object
    additionalProperties:
      type: string
  evententry:
    type: object
    properties:
      varlociraptor:
        type: array
        items: 
          type: string
      filter:
        type: string

properties:
  samples:
    type: string
  units:
    type: string

  ref:
    type: object
    properties:
      n_chromosomes:
        type: integer
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build
      - n_chromosomes

  epitope_prediction:
    type: object
    properties:
      activate:
        type: boolean
  
  affinity:
    type: object
    properties:
      netMHCpan:
        type: object
        properties:
          activate:
            type: boolean
          params:
            type: string
      netMHCIIpan:
        type: object
        properties:
          activate:
            type: boolean
          params:
            type: string

  HLAtyping:
    type: object
    properties:
      HLA_LA:
        type: object
        properties:
          activate:
            type: boolean

  fusion:
    type: object
    properties:
      arriba:
        type: object
        properties:
          activate:
            type: boolean
          blacklist:
            type: string
          params:
            type: string

  params:
    type: object
    properties:
      yara:
        type: string
      optitype:
        type: string
      microphaser:
        type: object
        properties:
          window_len:
            type: integer
          peptide_len:
            type: object
            properties:
              netMHCpan:
                type: integer
              netMHCIIpan:
                type: integer
          variant_sets:
            type: object
            properties:
              normal:
                type: string
              tumor:
                type: string
            required:
              - normal
              - tumor
        required:
          - window_len
          - peptide_len
          - variant_sets
    required:
      - yara
      - microphaser
      - optitype

required:
  - samples
  - units
  - ref
  - params
  - epitope_prediction
  - affinity
