$schema: "http://json-schema.org/draft-07/schema#"

description: snakemake configuration file

type: object

definitions:
  filterentry:
    type: object
    additionalProperties:
      type: string
  evententry:
    type: object
    properties:
      varlociraptor:
        type: array
        items: 
          type: string
      filter:
        type: string

properties:
  samples:
    type: string
  units:
    type: string

  ref:
    type: object
    properties:
      n_chromosomes:
        type: integer
      species:
        type: string
      release:
        type: integer
      build:
        type: string
    required:
      - species
      - release
      - build
      - n_chromosomes

  neoantigen_prediction:
    type: object
    properties:
      activate:
        type: boolean
  
  affinity:
    type: object
    properties:
  params:
    type: object
    properties:
      microphaser:
        type: object
        properties:
          variant_sets:
            type: object
            properties:
              normal:
                type: string
              tumor:
                type: string
            required:
              - normal
              - tumor
      net_mhc_pan:
        type: object
        properties:
          activate:
            type: boolean
          peptide_len:
            type: integer
          extra:
            type: string
          location:
            type: string
        required:
          - activate
      net_mhc_two_pan:
        type: object
        properties:
          activate:
            type: boolean
          peptide_len:
            type: integer
          extra:
            type: string
        required:
          - activate
    required:
      - microphaser
      - net_mhc_pan
      - net_mhc_two_pan


required:
  - samples
  - units
  - ref
  - params
  - epitope_prediction
  - affinity
